services:
  backend:
    container_name: concrete-backend
    build: ./backend
    restart: always
    networks:
      - tools-net

  frontend:
    container_name: concrete-frontend
    build: ./frontend
    restart: always
    ports:
      - "33018:80"
    depends_on:
      - backend
    networks:
      - tools-net

networks:
  tools-net:
    external: true
